/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visao;

import bibliotecaDAO.LivroDAO;
import bibliotecaDAO.UsuarioDAO;
import modelos.Livro;
import modelos.Usuario;

/**
 *
 * @author gusta
 */
public class TelaHome extends javax.swing.JPanel {

    private static TelaHome instancia;

    private TelaHome() {
        initComponents();
    }

    public static TelaHome getTelaHome(){
        if(instancia == null){
            instancia = new TelaHome();
        }
        return instancia;
    }

    public static void atalizaPaginaHome(){

        lbNomeUsuario.setText(UsuarioDAO.usuarioLogado.getNome());
        System.out.println(UsuarioDAO.usuarioLogado.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btColecao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfAddLivro = new javax.swing.JTextField();
        btAddLivro = new javax.swing.JButton();
        lbTextoConfirmacao = new javax.swing.JLabel();
        lbNomeUsuario = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Biblioteca Pessoal");

        btColecao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btColecao.setText("Coleção");
        btColecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColecaoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Adicionar livro:");

        jLabel3.setText("digite o nome do livro:");

        txfAddLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btAddLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btAddLivro.setText("Adicionar");
        btAddLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddLivroActionPerformed(evt);
            }
        });

        lbNomeUsuario.setText("nome usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAddLivro)
                    .addComponent(txfAddLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 71, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTextoConfirmacao)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(449, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(btColecao)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNomeUsuario)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbNomeUsuario)))
                .addGap(18, 18, 18)
                .addComponent(btColecao)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfAddLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAddLivro)
                .addGap(65, 65, 65)
                .addComponent(lbTextoConfirmacao)
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btColecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btColecaoActionPerformed
        TelaDinamica.home.setVisible(false);
        TelaDinamica.perfil.setVisible(true);
    }//GEN-LAST:event_btColecaoActionPerformed

    private void btAddLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddLivroActionPerformed
        
        Usuario usuario = UsuarioDAO.usuarioLogado;
        Livro livroAdicionado = new Livro();

        String nomeLivro = txfAddLivro.getText();
        livroAdicionado.setNome(nomeLivro);
        usuario.addLivro(livroAdicionado);
        
        Livro livro = (Livro) usuario.getLivrosUsuario().get(0);

        System.out.println(livro.getNome());
        
        if(LivroDAO.save(usuario)){
            System.out.println("Livro salvo");
            txfAddLivro.setText("");
            lbTextoConfirmacao.setText("Livro salvo");
            usuario.removeLivro();
        }
    }//GEN-LAST:event_btAddLivroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddLivro;
    private javax.swing.JButton btColecao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JLabel lbNomeUsuario;
    private javax.swing.JLabel lbTextoConfirmacao;
    private javax.swing.JTextField txfAddLivro;
    // End of variables declaration//GEN-END:variables
}
