/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visao;

import bibliotecaDAO.UsuarioDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelos.Usuario;

/**
 *
 * @author gusta
 */
public class TelaCadastro extends javax.swing.JPanel {

    private static TelaCadastro instancia;

    private TelaCadastro() {
        initComponents();
        painelErro.setVisible(false);
    }

    public static TelaCadastro getTelaCadastro(){
        if(instancia == null){
            instancia = new TelaCadastro();
        }
        return instancia;
    }

    public void limparCampos(){
    
        txfEmail.setText("");
        txfEmailConfirmar.setText("");
        txfSenha.setText("");
        txfSenhaConfirmar.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfEmailConfirmar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        btVoltarLogin = new javax.swing.JButton();
        painelErro = new javax.swing.JPanel();
        lblErro = new javax.swing.JLabel();
        txfSenha = new javax.swing.JPasswordField();
        txfSenhaConfirmar = new javax.swing.JPasswordField();
        cbMostrarSenha = new javax.swing.JCheckBox();

        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastrar-se:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("e-mail:");

        txfEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("confirme o e-mail:");

        txfEmailConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("senha:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("confirme a senha:");

        btCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btCadastrar.setText("Cadastrar-se");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("nome:");

        txfNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btVoltarLogin.setText("voltar");
        btVoltarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarLoginActionPerformed(evt);
            }
        });

        lblErro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErro.setForeground(new java.awt.Color(255, 0, 0));
        lblErro.setText("e-mail ou senha incorretos");

        javax.swing.GroupLayout painelErroLayout = new javax.swing.GroupLayout(painelErro);
        painelErro.setLayout(painelErroLayout);
        painelErroLayout.setHorizontalGroup(
            painelErroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelErroLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblErro)
                .addContainerGap())
        );
        painelErroLayout.setVerticalGroup(
            painelErroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelErroLayout.createSequentialGroup()
                .addComponent(lblErro)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        txfSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txfSenhaConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cbMostrarSenha.setText("Mostrar senha");
        cbMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMostrarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCadastrar)
                .addGap(188, 188, 188)
                .addComponent(btVoltarLogin)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMostrarSenha)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfSenhaConfirmar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                                .addComponent(painelErro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txfEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfEmailConfirmar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(171, 171, 171))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfEmailConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelErro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfSenhaConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMostrarSenha)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btVoltarLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCadastrar)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        boolean verificaUsuario = false;
        
        if(txfEmail.getText().equals(txfEmailConfirmar.getText()) && txfSenha.getText().equals(txfSenhaConfirmar.getText()) && (!txfEmail.getText().equals("") && !txfSenha.getText().equals("") && txfEmail.getText().contains("@"))){
            
            Usuario novoUsuario = new Usuario();
            novoUsuario.setEmail(txfEmail.getText());
            novoUsuario.setSenha(txfSenha.getText());
            novoUsuario.setNome(txfNome.getText());
            
            try {
                verificaUsuario = UsuarioDAO.save(novoUsuario);
                if(verificaUsuario){
                    TelaDinamica.home.setVisible(true);
                    TelaDinamica.cadastro.setVisible(false);
                }
            }catch (Exception ex) {
                Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }else if(!verificaUsuario) {
            System.out.println("Usuario ja existe");
            limparCampos();
        }else{
            painelErro.setVisible(true);
            limparCampos();
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btVoltarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarLoginActionPerformed
                
        TelaDinamica.login.setVisible(true);
        TelaDinamica.cadastro.setVisible(false);
    }//GEN-LAST:event_btVoltarLoginActionPerformed

    private void cbMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMostrarSenhaActionPerformed
        
        if(cbMostrarSenha.isSelected()){
            txfSenha.setEchoChar((char)0);
            txfSenhaConfirmar.setEchoChar((char)0);
        }else{
            txfSenha.setEchoChar('•');
            txfSenhaConfirmar.setEchoChar('•');
        }
    }//GEN-LAST:event_cbMostrarSenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btVoltarLogin;
    private javax.swing.JCheckBox cbMostrarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblErro;
    private javax.swing.JPanel painelErro;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfEmailConfirmar;
    private javax.swing.JTextField txfNome;
    private javax.swing.JPasswordField txfSenha;
    private javax.swing.JPasswordField txfSenhaConfirmar;
    // End of variables declaration//GEN-END:variables
}
